version: '3.1'
services:
  db:
    image: postgres
    container_name: school_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: fox
      POSTGRES_PASSWORD: foxminded
      POSTGRES_DB: school
  app:
    container_name: school_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    tty: true
    stdin_open: true